import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import './globals.css';
import { Theme } from '@radix-ui/themes';
import { BrowserAPIMock } from '@/shared/mock';

const isEnabledMocking = process.env.NEXT_PUBLIC_API_MOCKING === 'enabled';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <BrowserAPIMock enabledMocking={isEnabledMocking}>
            {children}
          </BrowserAPIMock>
        </Theme>
      </body>
    </html>
  );
}
