import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import './globals.css';
import { Theme } from '@radix-ui/themes';
import { BrowserAPIMock } from '@/shared/mock';
import { QueryClientProvider } from '@/app/config/query-client-provider';

const isEnabledMocking = process.env.NEXT_PUBLIC_API_MOCKING === 'enabled';

// const result = await UserService.getLoginUserInfo();
// const parsedData = LoginUserInfoDtoSchema.parse(result.data);
// console.log(parsedData);

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <BrowserAPIMock enabledMocking={isEnabledMocking}>
            <QueryClientProvider>{children}</QueryClientProvider>
          </BrowserAPIMock>
        </Theme>
      </body>
    </html>
  );
}
